// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/memos": {
            "get": {
                "description": "Get all memos",
                "tags": [
                    "Memo"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "memoID",
                        "name": "memoID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Memos"
                            }
                        }
                    },
                    "404": {},
                    "500": {}
                }
            }
        },
        "/memos/:memoID": {
            "get": {
                "description": "Get memo by memoID",
                "tags": [
                    "Memo"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "memoID",
                        "name": "memoID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Memos"
                        }
                    },
                    "404": {},
                    "500": {}
                }
            },
            "post": {
                "description": "Create memo",
                "tags": [
                    "Memo"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "memoID",
                        "name": "memoID",
                        "in": "query"
                    },
                    {
                        "description": "create memo",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateMemo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Message"
                        }
                    },
                    "404": {},
                    "500": {}
                }
            },
            "delete": {
                "description": "Update memo",
                "tags": [
                    "Memo"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "memoID",
                        "name": "memoID",
                        "in": "query"
                    },
                    {
                        "description": "update memo",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateMemo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Message"
                        }
                    },
                    "404": {},
                    "500": {}
                }
            }
        }
    },
    "definitions": {
        "models.Memos": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "requests.CreateMemo": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "requests.UpdateMemo": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "responses.Message": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Bolierplate CRUD API",
	Description: "This documentation describes bolierplate CRUD APIs",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
